module ysyx_25080209_AXI4_Arbiter_Xbar #(DATA_WID = 32, ADDR_WID = 32) (
    input clk, rst,

//AXI4接口 master0
    output                  io_master0_awready,
    input                   io_master0_awvalid,
    input  [ADDR_WID-1:0]   io_master0_awaddr,
    input  [3:0]            io_master0_awid,
    input  [7:0]            io_master0_awlen,
    input  [2:0]            io_master0_awsize,
    input  [1:0]            io_master0_awburst,
    output                  io_master0_wready,
    input                   io_master0_wvalid,
    input  [DATA_WID-1:0]   io_master0_wdata,
    input  [3:0]            io_master0_wstrb,
    input                   io_master0_wlast,
    input                   io_master0_bready,
    output                  io_master0_bvalid,
    output [1:0]            io_master0_bresp,
    output [3:0]            io_master0_bid,
    output                  io_master0_arready,
    input                   io_master0_arvalid,
    input  [ADDR_WID-1:0]   io_master0_araddr,
    input  [3:0]            io_master0_arid,
    input  [7:0]            io_master0_arlen,
    input  [2:0]            io_master0_arsize,
    input  [1:0]            io_master0_arburst,
    input                   io_master0_rready,
    output                  io_master0_rvalid,
    output [1:0]            io_master0_rresp,
    output [DATA_WID-1:0]   io_master0_rdata,
    output                  io_master0_rlast,
    output [3:0]            io_master0_rid,

//AXI4接口 master1
    output                  io_master1_awready,
    input                   io_master1_awvalid,
    input  [ADDR_WID-1:0]   io_master1_awaddr,
    input  [3:0]            io_master1_awid,
    input  [7:0]            io_master1_awlen,
    input  [2:0]            io_master1_awsize,
    input  [1:0]            io_master1_awburst,
    output                  io_master1_wready,
    input                   io_master1_wvalid,
    input  [DATA_WID-1:0]   io_master1_wdata,
    input  [3:0]            io_master1_wstrb,
    input                   io_master1_wlast,
    input                   io_master1_bready,
    output                  io_master1_bvalid,
    output [1:0]            io_master1_bresp,
    output [3:0]            io_master1_bid,
    output                  io_master1_arready,
    input                   io_master1_arvalid,
    input  [ADDR_WID-1:0]   io_master1_araddr,
    input  [3:0]            io_master1_arid,
    input  [7:0]            io_master1_arlen,
    input  [2:0]            io_master1_arsize,
    input  [1:0]            io_master1_arburst,
    input                   io_master1_rready,
    output                  io_master1_rvalid,
    output [1:0]            io_master1_rresp,
    output [DATA_WID-1:0]   io_master1_rdata,
    output                  io_master1_rlast,
    output [3:0]            io_master1_rid,

//AXI4接口 slave0
    input                   io_slave0_awready,
    output                  io_slave0_awvalid,
    output [31:0]           io_slave0_awaddr,
    output [3:0]            io_slave0_awid,
    output [7:0]            io_slave0_awlen,
    output [2:0]            io_slave0_awsize,
    output [1:0]            io_slave0_awburst,
    input                   io_slave0_wready,
    output                  io_slave0_wvalid,
    output [31:0]           io_slave0_wdata,
    output [3:0]            io_slave0_wstrb,
    output                  io_slave0_wlast,
    output                  io_slave0_bready,
    input                   io_slave0_bvalid,
    input [1:0]             io_slave0_bresp,
    input [3:0]             io_slave0_bid,
    input                   io_slave0_arready,
    output                  io_slave0_arvalid,
    output [31:0]           io_slave0_araddr,
    output [3:0]            io_slave0_arid,
    output [7:0]            io_slave0_arlen,
    output [2:0]            io_slave0_arsize,
    output [1:0]            io_slave0_arburst,
    output                  io_slave0_rready,
    input                   io_slave0_rvalid,
    input [1:0]             io_slave0_rresp,
    input [31:0]            io_slave0_rdata,
    input                   io_slave0_rlast,
    input [3:0]             io_slave0_rid,
//AXI4接口 slave1
    input                   io_slave1_awready,
    output                  io_slave1_awvalid,
    output [31:0]           io_slave1_awaddr,
    output [3:0]            io_slave1_awid,
    output [7:0]            io_slave1_awlen,
    output [2:0]            io_slave1_awsize,
    output [1:0]            io_slave1_awburst,
    input                   io_slave1_wready,
    output                  io_slave1_wvalid,
    output [31:0]           io_slave1_wdata,
    output [3:0]            io_slave1_wstrb,
    output                  io_slave1_wlast,
    output                  io_slave1_bready,
    input                   io_slave1_bvalid,
    input [1:0]             io_slave1_bresp,
    input [3:0]             io_slave1_bid,
    input                   io_slave1_arready,
    output                  io_slave1_arvalid,
    output [31:0]           io_slave1_araddr,
    output [3:0]            io_slave1_arid,
    output [7:0]            io_slave1_arlen,
    output [2:0]            io_slave1_arsize,
    output [1:0]            io_slave1_arburst,
    output                  io_slave1_rready,
    input                   io_slave1_rvalid,
    input [1:0]             io_slave1_rresp,
    input [31:0]            io_slave1_rdata,
    input                   io_slave1_rlast,
    input [3:0]             io_slave1_rid
);
wire                  xbar_awready;
wire                  xbar_awvalid;
wire [ADDR_WID-1:0]   xbar_awaddr;
wire [3:0]            xbar_awid;
wire [7:0]            xbar_awlen;
wire [2:0]            xbar_awsize;
wire [1:0]            xbar_awburst;

wire                  xbar_wready;
wire                  xbar_wvalid;
wire [DATA_WID-1:0]   xbar_wdata;
wire [3:0]            xbar_wstrb;
wire                  xbar_wlast;

wire                  xbar_bready;
wire                  xbar_bvalid;
wire [1:0]            xbar_bresp;
wire [3:0]            xbar_bid;

wire                  xbar_arready;
wire                  xbar_arvalid;
wire [ADDR_WID-1:0]   xbar_araddr;
wire [3:0]            xbar_arid;
wire [7:0]            xbar_arlen;
wire [2:0]            xbar_arsize;
wire [1:0]            xbar_arburst;

wire                  xbar_rready;
wire                  xbar_rvalid;
wire [1:0]            xbar_rresp;
wire [DATA_WID-1:0]   xbar_rdata;
wire                  xbar_rlast;
wire [3:0]            xbar_rid;

// Arbiter 与 Xbar 之间的握手信号
wire                  arbiter_valid;
wire                  xbar_valid;

//--------------------------------------------------------------------------
// 实例化：AXI4-Lite 仲裁器（双主设备 → 单主设备）
//--------------------------------------------------------------------------
ysyx_25080209_AXI4_Arbiter #(
    .DATA_WID(DATA_WID),
    .ADDR_WID(ADDR_WID)
) u_arbiter (
    .clk                    (clk),
    .rst                    (rst),

    .arbiter_valid          (arbiter_valid),
    .xbar_valid             (xbar_valid),

    .io_master0_awready     (io_master0_awready),
    .io_master0_awvalid     (io_master0_awvalid),
    .io_master0_awaddr      (io_master0_awaddr),
    .io_master0_awid        (io_master0_awid),
    .io_master0_awlen       (io_master0_awlen),
    .io_master0_awsize      (io_master0_awsize),
    .io_master0_awburst     (io_master0_awburst),
    .io_master0_wready      (io_master0_wready),
    .io_master0_wvalid      (io_master0_wvalid),
    .io_master0_wdata       (io_master0_wdata),
    .io_master0_wstrb       (io_master0_wstrb),
    .io_master0_wlast       (io_master0_wlast),
    .io_master0_bready      (io_master0_bready),
    .io_master0_bvalid      (io_master0_bvalid),
    .io_master0_bresp       (io_master0_bresp),
    .io_master0_bid         (io_master0_bid),
    .io_master0_arready     (io_master0_arready),
    .io_master0_arvalid     (io_master0_arvalid),
    .io_master0_araddr      (io_master0_araddr),
    .io_master0_arid        (io_master0_arid),
    .io_master0_arlen       (io_master0_arlen),
    .io_master0_arsize      (io_master0_arsize),
    .io_master0_arburst     (io_master0_arburst),
    .io_master0_rready      (io_master0_rready),
    .io_master0_rvalid      (io_master0_rvalid),
    .io_master0_rresp       (io_master0_rresp),
    .io_master0_rdata       (io_master0_rdata),
    .io_master0_rlast       (io_master0_rlast),
    .io_master0_rid         (io_master0_rid),

    .io_master1_awready     (io_master1_awready),
    .io_master1_awvalid     (io_master1_awvalid),
    .io_master1_awaddr      (io_master1_awaddr),
    .io_master1_awid        (io_master1_awid),
    .io_master1_awlen       (io_master1_awlen),
    .io_master1_awsize      (io_master1_awsize),
    .io_master1_awburst     (io_master1_awburst),
    .io_master1_wready      (io_master1_wready),
    .io_master1_wvalid      (io_master1_wvalid),
    .io_master1_wdata       (io_master1_wdata),
    .io_master1_wstrb       (io_master1_wstrb),
    .io_master1_wlast       (io_master1_wlast),
    .io_master1_bready      (io_master1_bready),
    .io_master1_bvalid      (io_master1_bvalid),
    .io_master1_bresp       (io_master1_bresp),
    .io_master1_bid         (io_master1_bid),
    .io_master1_arready     (io_master1_arready),
    .io_master1_arvalid     (io_master1_arvalid),
    .io_master1_araddr      (io_master1_araddr),
    .io_master1_arid        (io_master1_arid),
    .io_master1_arlen       (io_master1_arlen),
    .io_master1_arsize      (io_master1_arsize),
    .io_master1_arburst     (io_master1_arburst),
    .io_master1_rready      (io_master1_rready),
    .io_master1_rvalid      (io_master1_rvalid),
    .io_master1_rresp       (io_master1_rresp),
    .io_master1_rdata       (io_master1_rdata),
    .io_master1_rlast       (io_master1_rlast),
    .io_master1_rid         (io_master1_rid),

    .io_slave_awready       (xbar_awready),
    .io_slave_awvalid       (xbar_awvalid),
    .io_slave_awaddr        (xbar_awaddr),
    .io_slave_awid          (xbar_awid),
    .io_slave_awlen         (xbar_awlen),
    .io_slave_awsize        (xbar_awsize),
    .io_slave_awburst       (xbar_awburst),
    .io_slave_wready        (xbar_wready),
    .io_slave_wvalid        (xbar_wvalid),
    .io_slave_wdata         (xbar_wdata),
    .io_slave_wstrb         (xbar_wstrb),
    .io_slave_wlast         (xbar_wlast),
    .io_slave_bready        (xbar_bready),
    .io_slave_bvalid        (xbar_bvalid),
    .io_slave_bresp         (xbar_bresp),
    .io_slave_bid           (xbar_bid),
    .io_slave_arready       (xbar_arready),
    .io_slave_arvalid       (xbar_arvalid),
    .io_slave_araddr        (xbar_araddr),
    .io_slave_arid          (xbar_arid),
    .io_slave_arlen         (xbar_arlen),
    .io_slave_arsize        (xbar_arsize),
    .io_slave_arburst       (xbar_arburst),
    .io_slave_rready        (xbar_rready),
    .io_slave_rvalid        (xbar_rvalid),
    .io_slave_rresp         (xbar_rresp),
    .io_slave_rdata         (xbar_rdata),
    .io_slave_rlast         (xbar_rlast),
    .io_slave_rid           (xbar_rid)
);

ysyx_25080209_Xbar #(
    .DATA_WID(DATA_WID),
    .ADDR_WID(ADDR_WID)
) u_xbar (
    .clk                    (clk),
    .rst                    (rst),

    .arbiter_valid          (arbiter_valid),
    .xbar_valid             (xbar_valid),

    .io_master_awready      (xbar_awready),
    .io_master_awvalid      (xbar_awvalid),
    .io_master_awaddr       (xbar_awaddr),
    .io_master_awid         (xbar_awid),
    .io_master_awlen        (xbar_awlen),
    .io_master_awsize       (xbar_awsize),
    .io_master_awburst      (xbar_awburst),
    .io_master_wready       (xbar_wready),
    .io_master_wvalid       (xbar_wvalid),
    .io_master_wdata        (xbar_wdata),
    .io_master_wstrb        (xbar_wstrb),
    .io_master_wlast        (xbar_wlast),
    .io_master_bready       (xbar_bready),
    .io_master_bvalid       (xbar_bvalid),
    .io_master_bresp        (xbar_bresp),
    .io_master_bid          (xbar_bid),
    .io_master_arready      (xbar_arready),
    .io_master_arvalid      (xbar_arvalid),
    .io_master_araddr       (xbar_araddr),
    .io_master_arid         (xbar_arid),
    .io_master_arlen        (xbar_arlen),
    .io_master_arsize       (xbar_arsize),
    .io_master_arburst      (xbar_arburst),
    .io_master_rready       (xbar_rready),
    .io_master_rvalid       (xbar_rvalid),
    .io_master_rresp        (xbar_rresp),
    .io_master_rdata        (xbar_rdata),
    .io_master_rlast        (xbar_rlast),
    .io_master_rid          (xbar_rid),

    .io_slave0_awready      (io_slave0_awready),
    .io_slave0_awvalid      (io_slave0_awvalid),
    .io_slave0_awaddr       (io_slave0_awaddr),
    .io_slave0_awid         (io_slave0_awid),
    .io_slave0_awlen        (io_slave0_awlen),
    .io_slave0_awsize       (io_slave0_awsize),
    .io_slave0_awburst      (io_slave0_awburst),
    .io_slave0_wready       (io_slave0_wready),
    .io_slave0_wvalid       (io_slave0_wvalid),
    .io_slave0_wdata        (io_slave0_wdata),
    .io_slave0_wstrb        (io_slave0_wstrb),
    .io_slave0_wlast        (io_slave0_wlast),
    .io_slave0_bready       (io_slave0_bready),
    .io_slave0_bvalid       (io_slave0_bvalid),
    .io_slave0_bresp        (io_slave0_bresp),
    .io_slave0_bid          (io_slave0_bid),
    .io_slave0_arready      (io_slave0_arready),
    .io_slave0_arvalid      (io_slave0_arvalid),
    .io_slave0_araddr       (io_slave0_araddr),
    .io_slave0_arid         (io_slave0_arid),
    .io_slave0_arlen        (io_slave0_arlen),
    .io_slave0_arsize       (io_slave0_arsize),
    .io_slave0_arburst      (io_slave0_arburst),
    .io_slave0_rready       (io_slave0_rready),
    .io_slave0_rvalid       (io_slave0_rvalid),
    .io_slave0_rresp        (io_slave0_rresp),
    .io_slave0_rdata        (io_slave0_rdata),
    .io_slave0_rlast        (io_slave0_rlast),
    .io_slave0_rid          (io_slave0_rid),

    .io_slave1_awready      (io_slave1_awready),
    .io_slave1_awvalid      (io_slave1_awvalid),
    .io_slave1_awaddr       (io_slave1_awaddr),
    .io_slave1_awid         (io_slave1_awid),
    .io_slave1_awlen        (io_slave1_awlen),
    .io_slave1_awsize       (io_slave1_awsize),
    .io_slave1_awburst      (io_slave1_awburst),
    .io_slave1_wready       (io_slave1_wready),
    .io_slave1_wvalid       (io_slave1_wvalid),
    .io_slave1_wdata        (io_slave1_wdata),
    .io_slave1_wstrb        (io_slave1_wstrb),
    .io_slave1_wlast        (io_slave1_wlast),
    .io_slave1_bready       (io_slave1_bready),
    .io_slave1_bvalid       (io_slave1_bvalid),
    .io_slave1_bresp        (io_slave1_bresp),
    .io_slave1_bid          (io_slave1_bid),
    .io_slave1_arready      (io_slave1_arready),
    .io_slave1_arvalid      (io_slave1_arvalid),
    .io_slave1_araddr       (io_slave1_araddr),
    .io_slave1_arid         (io_slave1_arid),
    .io_slave1_arlen        (io_slave1_arlen),
    .io_slave1_arsize       (io_slave1_arsize),
    .io_slave1_arburst      (io_slave1_arburst),
    .io_slave1_rready       (io_slave1_rready),
    .io_slave1_rvalid       (io_slave1_rvalid),
    .io_slave1_rresp        (io_slave1_rresp),
    .io_slave1_rdata        (io_slave1_rdata),
    .io_slave1_rlast        (io_slave1_rlast),
    .io_slave1_rid          (io_slave1_rid)
);
endmodule
